#ifndef MK_HTTPCLIENT_H_
#define MK_HTTPCLIENT_H_

#include "mk_common.h"
#include "mk_events_objects.h"

#ifdef __cplusplus
extern "C" {
#endif

///////////////////////////////////////////HttpDownloader/////////////////////////////////////////////

typedef struct mk_http_downloader_t *mk_http_downloader;

/**
 * @param user_data User data pointer
 * @param code Error code, 0 represents success
 * @param err_msg Error message
 * @param file_path File save path
 */
typedef void(API_CALL *on_mk_download_complete)(void *user_data, int code, const char *err_msg, const char *file_path);

/**
 * Create http[s] downloader
 * @return Downloader pointer
 */
API_EXPORT mk_http_downloader API_CALL mk_http_downloader_create();

/**
 * Destroy http[s] downloader
 * @param ctx Downloader pointer
 */
API_EXPORT void API_CALL mk_http_downloader_release(mk_http_downloader ctx);

/**
 * Start http[s] download
 * @param ctx Downloader pointer
 * @param url http[s] download url
 * @param file File save path
 * @param cb Callback function
 * @param user_data User data pointer
 */
API_EXPORT void API_CALL mk_http_downloader_start(mk_http_downloader ctx, const char *url, const char *file, on_mk_download_complete cb, void *user_data);
API_EXPORT void API_CALL mk_http_downloader_start2(mk_http_downloader ctx, const char *url, const char *file, on_mk_download_complete cb, void *user_data, on_user_data_free user_data_free);

///////////////////////////////////////////HttpRequester/////////////////////////////////////////////
typedef struct mk_http_requester_t *mk_http_requester;

/**
 * Http request result callback
 * When code == 0, it means that the current http session is complete (http response has been received)
 * Users should get the mk_http_requester object through user_data
 * Then get the relevant response data through functions such as mk_http_requester_get_response
 * At the end of the callback, the object should be destroyed by calling the mk_http_requester_release function
 * Or reuse the object after calling the mk_http_requester_clear function
 * @param user_data User data pointer
 * @param code Error code, 0 represents success
 * @param err_msg Error message
 */
typedef void(API_CALL *on_mk_http_requester_complete)(void *user_data, int code, const char *err_msg);

/**
 * Create HttpRequester
 */
API_EXPORT mk_http_requester API_CALL mk_http_requester_create();

/**
 * This method is only needed when reusing the mk_http_requester object
 */
API_EXPORT void API_CALL mk_http_requester_clear(mk_http_requester ctx);

/**
 * Destroy HttpRequester
 * If the mk_http_requester_start function is called and is waiting for the http response,
 * You can also call the mk_http_requester_release method to cancel the current http request
 */
API_EXPORT void API_CALL mk_http_requester_release(mk_http_requester ctx);

/**
 * Set HTTP method, such as GET/POST
 */
API_EXPORT void API_CALL mk_http_requester_set_method(mk_http_requester ctx,const char *method);

/**
 * Batch set HTTP headers
 * @param header For example, {"Content-Type","text/html",NULL} must end with NULL
 */
API_EXPORT void API_CALL mk_http_requester_set_header(mk_http_requester ctx, const char *header[]);

/**
 * Add HTTP header
 * @param key For example, Content-Type
 * @param value For example, text/html
 * @param force If the key already exists, whether to force replacement
 */
API_EXPORT void API_CALL mk_http_requester_add_header(mk_http_requester ctx,const char *key,const char *value,int force);

/**
 * Set message body,
 * @param body mk_http_body object, generated by functions such as mk_http_body_from_string, please call mk_http_body_release to release it after use
 */
API_EXPORT void API_CALL mk_http_requester_set_body(mk_http_requester ctx, mk_http_body body);

/**
 * You can call this method to get the status code after receiving the HTTP response
 * @return For example, 200 OK
 */
API_EXPORT const char* API_CALL mk_http_requester_get_response_status(mk_http_requester ctx);

/**
 * You can call this method to get the response HTTP header after receiving the HTTP response
 * @param key HTTP header key name
 * @return HTTP header key value
 */
API_EXPORT const char* API_CALL mk_http_requester_get_response_header(mk_http_requester ctx,const char *key);

/**
 * You can call this method to get the response HTTP body after receiving the HTTP response
 * @param length Return body length, can be null
 * @return Body pointer
 */
API_EXPORT const char* API_CALL mk_http_requester_get_response_body(mk_http_requester ctx, size_t *length);

/**
 * You can call this method to get the response after receiving the HTTP response
 * @return Response object
 */
API_EXPORT mk_parser API_CALL mk_http_requester_get_response(mk_http_requester ctx);

/**
 * Set callback function
 * @param cb Callback function, cannot be empty
 * @param user_data User data pointer
 */
API_EXPORT void API_CALL mk_http_requester_set_cb(mk_http_requester ctx,on_mk_http_requester_complete cb, void *user_data);
API_EXPORT void API_CALL mk_http_requester_set_cb2(mk_http_requester ctx,on_mk_http_requester_complete cb, void *user_data, on_user_data_free user_data_free);

/**
 * Start url request
 * @param url Request url, supports http/https
 * @param timeout_second Maximum timeout time
 */
API_EXPORT void API_CALL mk_http_requester_start(mk_http_requester ctx,const char *url, float timeout_second);

#ifdef __cplusplus
}
#endif

#endif /* MK_HTTPCLIENT_H_ */
