#ifndef MK_PUSHER_H
#define MK_PUSHER_H

#include "mk_common.h"
#include "mk_events_objects.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct mk_pusher_t *mk_pusher;

/**
 * Callback for streaming result or streaming interruption event
 * @param user_data User data pointer
 * @param err_code Error code, 0 for success
 * @param err_msg Error message
 */
typedef void(API_CALL *on_mk_push_event)(void *user_data,int err_code,const char *err_msg);

/**
 * Bind the MediaSource object and create an rtmp[s]/rtsp[s] pusher
 * MediaSource is generated by mk_media_create or mk_proxy_player_create or streaming
 * The MediaSource object must be registered
 * @param schema Protocol to which the bound MediaSource object belongs, supporting rtsp/rtmp
 * @param vhost Virtual host of the bound MediaSource object, generally __defaultVhost__
 * @param app Application name of the bound MediaSource object, generally live
 * @param stream Stream id of the bound MediaSource object
 * @return Object pointer
 */
API_EXPORT mk_pusher API_CALL mk_pusher_create(const char *schema,const char *vhost,const char *app, const char *stream);

/**
 * Bind the MediaSource object and create an rtmp[s]/rtsp[s] pusher
 * MediaSource is generated by mk_media_create or mk_proxy_player_create or streaming
 * The MediaSource object must be registered
 * @param src MediaSource object
 * @return Object pointer
 */
API_EXPORT mk_pusher API_CALL mk_pusher_create_src(mk_media_source src);

/**
 * Release the pusher
 * @param ctx Pusher pointer
 */
API_EXPORT void API_CALL mk_pusher_release(mk_pusher ctx);

/**
 * Set the pusher configuration options
 * @param ctx Pusher pointer
 * @param key Configuration item key, supports net_adapter/rtp_type/rtsp_user/rtsp_pwd/protocol_timeout_ms/media_timeout_ms/beat_interval_ms
 * @param val Configuration item value, if it is an integer, it needs to be converted to a unified string
 */
API_EXPORT void API_CALL mk_pusher_set_option(mk_pusher ctx, const char *key, const char *val);

/**
 * Start streaming
 * @param ctx Pusher pointer
 * @param url Streaming address, supports rtsp[s]/rtmp[s]
 */
API_EXPORT void API_CALL mk_pusher_publish(mk_pusher ctx,const char *url);

/**
 * Set the pusher streaming result callback function
 * @param ctx Pusher pointer
 * @param cb Callback function pointer, must not be null
 * @param user_data User data pointer
 */
API_EXPORT void API_CALL mk_pusher_set_on_result(mk_pusher ctx, on_mk_push_event cb, void *user_data);
API_EXPORT void API_CALL mk_pusher_set_on_result2(mk_pusher ctx, on_mk_push_event cb, void *user_data, on_user_data_free user_data_free);

/**
 * Set the callback for the streaming being abnormally interrupted
 * @param ctx Pusher pointer
 * @param cb Callback function pointer, must not be null
 * @param user_data User data pointer
 */
API_EXPORT void API_CALL mk_pusher_set_on_shutdown(mk_pusher ctx, on_mk_push_event cb, void *user_data);
API_EXPORT void API_CALL mk_pusher_set_on_shutdown2(mk_pusher ctx, on_mk_push_event cb, void *user_data, on_user_data_free user_data_free);

#ifdef __cplusplus
}
#endif
#endif //MK_PUSHER_H
