#ifdef ENABLE_MP4
#include <signal.h>
#include <iostream>
#include "Util/logger.h"
#include "Common/config.h"
#include "Common/Parser.h"
#include "Poller/EventPoller.h"
#include "Pusher/MediaPusher.h"
#include "Record/MP4Reader.h"

using namespace std;
using namespace toolkit;
using namespace mediakit;

// This is where the main function is actually executed, you can change the function name (domain) to main, and then you can enter a custom URL
int domain(const string &file, const string &url) {
    // Set log
    Logger::Instance().add(std::make_shared<ConsoleChannel>());
    Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>());

    // Close all protocol conversions
    mINI::Instance()[Protocol::kEnableMP4] = 0;
    mINI::Instance()[Protocol::kEnableFMP4] = 0;
    mINI::Instance()[Protocol::kEnableHls] = 0;
    mINI::Instance()[Protocol::kEnableHlsFmp4] = 0;
    mINI::Instance()[Protocol::kEnableTS] = 0;
    mINI::Instance()[Protocol::kEnableRtsp] = 0;
    mINI::Instance()[Protocol::kEnableRtmp] = 0;

    // Get the media protocol type based on the URL, note the case
    auto schema = strToLower(findSubString(url.data(), nullptr, "://").substr(0, 4));
    if (schema == "webr") {
        schema = "rtsp";
    }

    // Only enable the protocol conversion corresponding to the push protocol
    mINI::Instance()["protocol.enable_" + schema] = 1;

    // Load the MediaSource object from the mp4 file
    auto tuple = MediaTuple {DEFAULT_VHOST, "live", "stream", ""};
    auto reader = std::make_shared<MP4Reader>(tuple, file);
    // Start loading the mp4, set ref_self to false, so that the reader object can be set to nullptr to cancel, file_repeat can be set to empty, so that the file is read and the push stream is stopped
    reader->startReadMP4(100, false, true);
    auto src = MediaSource::find(schema, DEFAULT_VHOST, "live", "stream", false);

    if (!src) {
        // File does not exist
        WarnL << "File not existed: " << file;
        return -1;
    }

    // Select a poller thread to bind
    auto poller = EventPollerPool::Instance().getPoller();
    // Create a pusher and bind a MediaSource
    auto pusher = std::make_shared<MediaPusher>(src, poller);

    std::weak_ptr<MediaSource> weak_src = src;
    // src is used up, can be set to empty directly, to prevent the main function from holding it (MP4Reader holds it)
    src = nullptr;

    // You can specify the rtsp push method, support tcp and udp methods, default tcp
    //(*pusher)[Client::kRtpType] = Rtsp::RTP_UDP;

    // Set the interrupt handling logic during pushing
    std::weak_ptr<MediaPusher> weak_pusher = pusher;
    pusher->setOnShutdown([poller, url, weak_pusher, weak_src](const SockException &ex) {
        if (!weak_src.lock()) {
            // Media cancellation causes push interruption, no retry push
            WarnL << "MediaSource released:" << ex << ", publish stopped";
            return;
        }
        WarnL << "Server connection is closed:" << ex << ", republish after 2 seconds";
        // Repush, retry after 2 seconds
        poller->doDelayTask(2 * 1000, [weak_pusher, url]() {
            if (auto strong_push = weak_pusher.lock()) {
                strong_push->publish(url);
            }
            return 0;
        });
    });

    // Set the publish result handling logic
    pusher->setOnPublished([poller, weak_pusher, url](const SockException &ex) {
        if (!ex) {
            InfoL << "Publish success, please play with player:" << url;
            return;
        }

        WarnL << "Publish fail:" << ex << ", republish after 2 seconds";
        // If the publish fails, retry
        poller->doDelayTask(2 * 1000, [weak_pusher, url]() {
            if (auto strong_push = weak_pusher.lock()) {
                strong_push->publish(url);
            }
            return 0;
        });
    });
    pusher->publish(url);

    // sleep(5);
    // reader set to empty can terminate the push-related resources
    // reader = nullptr;

    // Set the exit signal processing function
    static semaphore sem;
    signal(SIGINT, [](int) { sem.post(); }); // Set the exit signal
    sem.wait();
    return 0;
}

int main(int argc, char *argv[]) {
    // You can use the mp4 file generated by test_server
    // File uses absolute path, push URL supports rtsp and rtmp
    // return domain("/Users/xiongziliang/Downloads/mp4/Quantum.mp4", "rtsp://127.0.0.1/live/rtsp_push");
    return domain(argv[1], argv[2]);
}
#endif