#include "MonitorProxy.h"
#include "Common/config.h"
#include "Util/MD5.h"
#include "Util/logger.h"
#include "Util/mini.h"

using namespace std;
using namespace toolkit;

namespace managerkit {

MonitorProxy::MonitorProxy()
    const ResourceTuple &tuple, const ResourceOption &option, int retry_count,
    const toolkit::EventPoller::Ptr &poller, int reconnect_delay_min, int reconnect_delay_max, int reconnect_delay_step)
    : ResourceMonitor(poller), _tuple(tuple), _option(option) {
    _retry_count = retry_count;

    setOnClose(nullptr);
    setOnConnect(nullptr);
    setOnDisconnect(nullptr);
    
    _reconnect_delay_min = reconnect_delay_min > 0 ? reconnect_delay_min : 2;
    _reconnect_delay_max = reconnect_delay_max > 0 ? reconnect_delay_max : 60;
    _reconnect_delay_step = reconnect_delay_step > 0 ? reconnect_delay_step : 3;
    _live_secs = 0;
    _live_status = 1;
    _repull_count = 0;
    (*this)[Client::kWaitTrackReady] = false;
}

void MonitorProxy::setPlayCallbackOnce(function<void(const SockException &ex)> cb) {
    _on_play = std::move(cb);
}

void MonitorProxy::setOnClose(function<void(const SockException &ex)> cb) {
    _on_close = cb ? std::move(cb) : [](const SockException &) {};
}

void MonitorProxy::setOnDisconnect(std::function<void()> cb) {
    _on_disconnect = cb ? std::move(cb) : [] () {};
}

void MonitorProxy::setOnConnect(std::function<void(const TranslationInfo&)> cb) {
    _on_connect = cb ? std::move(cb) : [](const TranslationInfo&) {};
}

void MonitorProxy::setTranslationInfo()
{
    _transtalion_info.byte_speed = _media_src ? _media_src->getBytesSpeed() : -1;
    _transtalion_info.start_time_stamp = _media_src ? _media_src->getCreateStamp() : 0;
    _transtalion_info.stream_info.clear();
    auto tracks = _muxer->getTracks();
    for (auto &track : tracks) {
        track->update();
        _transtalion_info.stream_info.emplace_back();
        auto &back = _transtalion_info.stream_info.back();
        back.track_type = track->getTrackType();
        back.track_name = track->getTrackName();
        //todo:
        switch (back.track_type) {
            default:
                break;
        }
    }
}

static int getMaxTrackSize(const std::string &url) {
    return 1;
}

void MonitorProxy::play(const string &strUrlTmp) {
    _option.max_track = getMaxTrackSize(strUrlTmp);
    weak_ptr<MonitorProxy> weak_ptr = shared_from_this();
    std::shared_ptr<int> piFailedCnt(new int(0)); // Number of consecutive playback failures
    setOnPlayResult([weak_ptr, strUrlTmp, piFailedCnt](const SockException &err) {
        auto strongSelf = weakSelf.lock();
        if (!strongSelf) {
            return;
        }

        if (strongSelf->_on_play) {
            strongSelf->_on_play(err);
            strongSelf->_on_play = nullptr;
        }

        if (!err) {
            // Cancel the timer to avoid the situation where the http stream index file fails to reconnect due to network fluctuations and then retries in a loop after successful reconnection
            strongSelf->_timer.reset();
            strongSelf->_live_ticker.resetTime();
            strongSelf->_live_status = 0;
            // Play successfully
            *piFailedCnt = 0; // The number of consecutive playback failed 0
            strongSelf->onPlaySuccess();
            strongSelf->setTranslationInfo();
            strongSelf->_on_connect(strongSelf->_transtalion_info);  

            InfoL << "play " << strUrlTmp << " success";
        } else if (*piFailedCnt < strongSelf->_retry_count || strongSelf->_retry_count < 0) {
            // Play failed, retry playing with delay
            strongSelf->_on_disconnect();
            strongSelf->rePlay(strUrlTmp, (*piFailedCnt)++);
        } else {
            // Reached the maximum number of retries, callback to close
            strongSelf->_on_close(err);
        }
    });

    setOnShutdown([weak_ptr, strUrlTmp, piFailedCnt](const SockException &err) {
        auto strongSelf = weakSelf.lock();
        if (!strongSelf) {
            return;
        }

        // Unregister the stream generated by the direct stream proxy
        strongSelf->setMediaSource(nullptr);

        if (strongSelf->_muxer) {
            auto tracks = strongSelf->ResourceMonitor::getTracks(false);
            for (auto &track : tracks) {
                track->delDelegate(strongSelf->_muxer.get());
            }

            // todo:
            // GET_CONFIG(bool, reset_when_replay, xGeneral::kResetWhenRePlay);
            // if (reset_when_replay) {
            //     strongSelf->_muxer.reset();
            // } else {
            //     strongSelf->_muxer->resetTracks();
            // }
        }

        if (*piFailedCnt == 0) {
            // Update the duration for the first time
            strongSelf->_live_secs += strongSelf->_live_ticker.elapsedTime() / 1000;
            strongSelf->_live_ticker.resetTime();
            TraceL << " live secs " << strongSelf->_live_secs;
        }

        // Play interrupted abnormally, retry playing with delay
        if (*piFailedCnt < strongSelf->_retry_count || strongSelf->_retry_count < 0) {
            strongSelf->_repull_count++;
            strongSelf->rePlay(strUrlTmp, (*piFailedCnt)++);
        } else {
            // Reached the maximum number of retries, callback to close
            strongSelf->_on_close(err);
        }
    });
    try {
        ResourceMonitor::play(strUrlTmp);
    } catch (std::exception &ex) {
        ErrorL << ex.what();
        onPlayResult(SockException(Err_other, ex.what()));
        return;
    }
    _pull_url = strUrlTmp;
    setDirectProxy();
}

void MonitorProxy::setDirectProxy() {
    Resource::Ptr resource;
    // todo: using with keep connect protocol
    if (resource) {
        setResource(resource);
    }
}

MonitorProxy::~MonitorProxy() {
    _timer.reset();
    // Avoid forgetting to callback api request when destructing
    if (_on_play) {
        try {
            _on_play(SockException(Err_shutdown, "player proxy close"));
        } catch(std::exception &ex) {
            WarnL << "Exception occurred: " << ex.what();
        }
        _on_play = nullptr;
    }
}

void MontiorProxy::rePlay(const string &strUrl, int iFailedCnt) {
    auto iDelay = MAX(_reconnect_delay_min * 1000, MIN(iFailedCnt * _reconnect_delay_step * 1000, _reconnect_delay_max * 1000));
    weak_ptr<MontiorProxy> weakSelf = shared_from_this();
    _timer = std::make_shared<Timer>(
        iDelay / 1000.0f,
        [weak_ptr, strUrl, iFailedCnt]() {
            // The more times the playback fails, the longer the delay
            auto strongMonitor = weakSelf.lock();
            if (!strongMonitor) {
                return false;
            }
            WarnL << "Try playback again[" << iFailedCnt << "]:" << strUrl;
            strongMonitor->ResourceMonitor::play(strUrl);
            strongMonitor->setDirectProxy();
            return false;
        },
        getPoller());
}

bool MonitorProxy::close(Resource &sender) {
    // Notify it to stop pushing the stream
    weak_ptr<MonitorProxy> weakSelf = dynamic_pointer_cast<MonitorProxy>
}

} // namespace managerkit